# permissions for end users to edit servicebindingingresses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: servicebindingingress-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: service-bind-ingress-operator
    app.kubernetes.io/part-of: service-bind-ingress-operator
    app.kubernetes.io/managed-by: kustomize
  name: servicebindingingress-editor-role
rules:
- apiGroups:
  - service-bind-ingress.bailu.io
  resources:
  - servicebindingingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - service-bind-ingress.bailu.io
  resources:
  - servicebindingingresses/status
  verbs:
  - get
